### ISSUE TITLE
Allow usernames to start with a number

### ISSUE THREAD

**Issue by 3ventic** [strawpoll/strawpoll#29]
In response to this on the beta site:

![](https://i.3v.fi/raw/1436833613.png)

Not being able to start the username with a number is the biggest issue of my online identity and I would like to keep consistency on strawpoll as well. Please allow usernames to start with a number. If there's a technical limitation to it, I would like to know it so I can learn.

**Comment by dandirks** [comment]
Thanks for the suggestion. The username stuff has been pushed back to a later release due to some issues that I can't resolve at the present time, unfortunately. I will look into reevaluating the naming requirements when I look at pushing username support live again, and I will take this into account.
